,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,user,labels,state,locked,assignee,assignees,milestone,comments,created_at,updated_at,closed_at,author_association,active_lock_reason,body,reactions,timeline_url,performed_via_github_app,draft,pull_request
0,https://api.github.com/repos/pandas-dev/pandas/issues/46093,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46093/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46093/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46093/events,https://github.com/pandas-dev/pandas/issues/46093,1145633879,I_kwDOAA0YD85ESPxX,46093,BUG: Exception for ExtensionDtype with missing attributes not very helpful,"{'login': 'datapythonista', 'id': 10058240, 'node_id': 'MDQ6VXNlcjEwMDU4MjQw', 'avatar_url': 'https://avatars.githubusercontent.com/u/10058240?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/datapythonista', 'html_url': 'https://github.com/datapythonista', 'followers_url': 'https://api.github.com/users/datapythonista/followers', 'following_url': 'https://api.github.com/users/datapythonista/following{/other_user}', 'gists_url': 'https://api.github.com/users/datapythonista/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/datapythonista/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/datapythonista/subscriptions', 'organizations_url': 'https://api.github.com/users/datapythonista/orgs', 'repos_url': 'https://api.github.com/users/datapythonista/repos', 'events_url': 'https://api.github.com/users/datapythonista/events{/privacy}', 'received_events_url': 'https://api.github.com/users/datapythonista/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 849023693, 'node_id': 'MDU6TGFiZWw4NDkwMjM2OTM=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/ExtensionArray', 'name': 'ExtensionArray', 'color': '6138b5', 'default': False, 'description': 'Extending pandas with custom dtypes or arrays.'}]",open,False,,[],,0,2022-02-21T10:52:50Z,2022-02-21T10:52:50Z,,MEMBER,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas
from pandas.core.dtypes.dtypes import register_extension_dtype, PandasExtensionDtype

@register_extension_dtype
class FooType(PandasExtensionDtype):
    pass

series = pandas.Series([1, 2, 3], dtype='foo')
```


### Issue Description

When implementing a pandas dtype, a `name` attribute is required for the class. When it's not present, the reported error is far from useful:

```
Traceback (most recent call last):
  File ""<stdin>"", line 1, in <module>
  File ""/home/mgarcia/src/pandas/pandas/core/series.py"", line 386, in __init__
    dtype = self._validate_dtype(dtype)
  File ""/home/mgarcia/src/pandas/pandas/core/generic.py"", line 431, in _validate_dtype
    dtype = pandas_dtype(dtype)
  File ""/home/mgarcia/src/pandas/pandas/core/dtypes/common.py"", line 1770, in pandas_dtype
    result = registry.find(dtype)
  File ""/home/mgarcia/src/pandas/pandas/core/dtypes/base.py"", line 492, in find
    return dtype_type.construct_from_string(dtype)
  File ""/home/mgarcia/src/pandas/pandas/core/dtypes/base.py"", line 281, in construct_from_string
    assert isinstance(cls.name, str), (cls, type(cls.name))
AssertionError: (<class '__main__.FooType'>, <class 'property'>)
```

### Expected Behavior

The example should raise an exception complaining of `FooType` missing a required `name` attribute.

Is there a reason why we aren't using an abstract class for `ExtensionDtype` with abstract methods for the required methods, instead of the lazy `AbstractMethodError` call? If we weren't about to instantiate the class, I'd understand, but looks like we're creating an instance. So, just the standard way of decorating the required methods as `abstracmethod` and making sure we create the instance before any use, would provide the expected behavior for free.

### Installed Versions

<details>

>>> import pandas
>>> pandas.show_versions()

INSTALLED VERSIONS
------------------
commit           : afc06e780e267b7eaac8651c7feb53f682d5b4a9
python           : 3.10.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.11.22-100.fc32.x86_64
Version          : #1 SMP Wed May 19 18:58:25 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.5.0.dev0+385.gafc06e780e.dirty
numpy            : 1.22.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 22.0.3
setuptools       : None
Cython           : None
pytest           : 7.0.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None


</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46093/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46093/timeline,,,
1,https://api.github.com/repos/pandas-dev/pandas/issues/46092,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46092/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46092/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46092/events,https://github.com/pandas-dev/pandas/issues/46092,1145582307,I_kwDOAA0YD85ESDLj,46092,BUG: object of type 'int' has no len() in from_dict function,"{'login': 'envytails', 'id': 8548750, 'node_id': 'MDQ6VXNlcjg1NDg3NTA=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8548750?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/envytails', 'html_url': 'https://github.com/envytails', 'followers_url': 'https://api.github.com/users/envytails/followers', 'following_url': 'https://api.github.com/users/envytails/following{/other_user}', 'gists_url': 'https://api.github.com/users/envytails/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/envytails/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/envytails/subscriptions', 'organizations_url': 'https://api.github.com/users/envytails/orgs', 'repos_url': 'https://api.github.com/users/envytails/repos', 'events_url': 'https://api.github.com/users/envytails/events{/privacy}', 'received_events_url': 'https://api.github.com/users/envytails/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-02-21T10:08:44Z,2022-02-21T10:08:44Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
d={ 'a': [3,2],'b':2}
pandas.DataFrame.from_dict(d,orient='index')
```


### Issue Description

```
d={ 'b':2,'a': [3,2],}
pandas.DataFrame.from_dict(d,orient='index')
```
gives no problem , but if i change the dict order I get `I get object of type 'int' has no len()`

### Expected Behavior

d={ 'b':2,'a': [3,2],}
pandas.DataFrame.from_dict(d,orient='index')

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 7d32926db8f7541c356066dcadabf854487738de
python           : 3.8.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-26-generic
Version          : #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : it_IT.UTF-8
LOCALE           : it_IT.UTF-8

pandas           : 1.2.2
numpy            : 1.19.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 22.0.2
setuptools       : 49.2.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.18.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : None
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
xlwt             : None
numba            : None


</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46092/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46092/timeline,,,
2,https://api.github.com/repos/pandas-dev/pandas/issues/46091,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46091/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46091/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46091/events,https://github.com/pandas-dev/pandas/pull/46091,1145316506,PR_kwDOAA0YD84zNC-w,46091,TST: Split & parameterize,"{'login': 'mroeschke', 'id': 10647082, 'node_id': 'MDQ6VXNlcjEwNjQ3MDgy', 'avatar_url': 'https://avatars.githubusercontent.com/u/10647082?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mroeschke', 'html_url': 'https://github.com/mroeschke', 'followers_url': 'https://api.github.com/users/mroeschke/followers', 'following_url': 'https://api.github.com/users/mroeschke/following{/other_user}', 'gists_url': 'https://api.github.com/users/mroeschke/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mroeschke/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mroeschke/subscriptions', 'organizations_url': 'https://api.github.com/users/mroeschke/orgs', 'repos_url': 'https://api.github.com/users/mroeschke/repos', 'events_url': 'https://api.github.com/users/mroeschke/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mroeschke/received_events', 'type': 'User', 'site_admin': False}","[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2ODU=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Testing', 'name': 'Testing', 'color': 'C4A000', 'default': False, 'description': 'pandas testing functions or related to the test suite'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/92', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92/labels', 'id': 7530006, 'node_id': 'MI_kwDOAA0YD84AcuYW', 'number': 92, 'title': '1.5', 'description': '', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 37, 'closed_issues': 343, 'state': 'open', 'created_at': '2021-12-31T21:51:13Z', 'updated_at': '2022-02-21T04:42:32Z', 'due_on': '2022-06-30T07:00:00Z', 'closed_at': None}",0,2022-02-21T04:42:32Z,2022-02-21T04:42:32Z,,MEMBER,,"- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46091/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46091/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46091', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46091', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46091.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46091.patch', 'merged_at': None}"
3,https://api.github.com/repos/pandas-dev/pandas/issues/46090,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46090/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46090/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46090/events,https://github.com/pandas-dev/pandas/pull/46090,1145279840,PR_kwDOAA0YD84zM7Ly,46090,REF: share hashtable_func_helper code,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-02-21T03:34:53Z,2022-02-21T03:34:53Z,,MEMBER,,"- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46090/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46090/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46090', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46090', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46090.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46090.patch', 'merged_at': None}"
4,https://api.github.com/repos/pandas-dev/pandas/issues/46089,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46089/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46089/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46089/events,https://github.com/pandas-dev/pandas/pull/46089,1145244468,PR_kwDOAA0YD84zM0Kb,46089,REF: use fused types for mode,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-02-21T02:27:29Z,2022-02-21T02:27:29Z,,MEMBER,,"- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Broken off of branch aimed at #45776.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46089/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46089/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46089', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46089', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46089.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46089.patch', 'merged_at': None}"
5,https://api.github.com/repos/pandas-dev/pandas/issues/46088,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46088/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46088/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46088/events,https://github.com/pandas-dev/pandas/issues/46088,1145213061,I_kwDOAA0YD85EQpCF,46088,"QST: For the resample of pandas, what happens if the corresponding data is missing from the dataset?","{'login': 'jiahe224', 'id': 35186992, 'node_id': 'MDQ6VXNlcjM1MTg2OTky', 'avatar_url': 'https://avatars.githubusercontent.com/u/35186992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jiahe224', 'html_url': 'https://github.com/jiahe224', 'followers_url': 'https://api.github.com/users/jiahe224/followers', 'following_url': 'https://api.github.com/users/jiahe224/following{/other_user}', 'gists_url': 'https://api.github.com/users/jiahe224/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jiahe224/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jiahe224/subscriptions', 'organizations_url': 'https://api.github.com/users/jiahe224/orgs', 'repos_url': 'https://api.github.com/users/jiahe224/repos', 'events_url': 'https://api.github.com/users/jiahe224/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jiahe224/received_events', 'type': 'User', 'site_admin': False}","[{'id': 34444536, 'node_id': 'MDU6TGFiZWwzNDQ0NDUzNg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Usage%20Question', 'name': 'Usage Question', 'color': '0052cc', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-02-21T01:27:10Z,2022-02-21T01:27:10Z,,NONE,,"### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).


### Link to question on StackOverflow

https://stackoverflow.com/questions/71167504/for-the-resample-of-pandas-what-happens-if-the-corresponding-data-is-missing-fr?noredirect=1#comment125800668_71167504

### Question about pandas

_No response_","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46088/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46088/timeline,,,
6,https://api.github.com/repos/pandas-dev/pandas/issues/46087,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46087/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46087/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46087/events,https://github.com/pandas-dev/pandas/pull/46087,1145121274,PR_kwDOAA0YD84zMcDj,46087,ENH: Improve error message when rolling over NaT value,"{'login': 'mroeschke', 'id': 10647082, 'node_id': 'MDQ6VXNlcjEwNjQ3MDgy', 'avatar_url': 'https://avatars.githubusercontent.com/u/10647082?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mroeschke', 'html_url': 'https://github.com/mroeschke', 'followers_url': 'https://api.github.com/users/mroeschke/followers', 'following_url': 'https://api.github.com/users/mroeschke/following{/other_user}', 'gists_url': 'https://api.github.com/users/mroeschke/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mroeschke/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mroeschke/subscriptions', 'organizations_url': 'https://api.github.com/users/mroeschke/orgs', 'repos_url': 'https://api.github.com/users/mroeschke/repos', 'events_url': 'https://api.github.com/users/mroeschke/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mroeschke/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1045950827, 'node_id': 'MDU6TGFiZWwxMDQ1OTUwODI3', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Window', 'name': 'Window', 'color': 'd4c5f9', 'default': False, 'description': 'rolling, ewma, expanding'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/92', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92/labels', 'id': 7530006, 'node_id': 'MI_kwDOAA0YD84AcuYW', 'number': 92, 'title': '1.5', 'description': '', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 37, 'closed_issues': 343, 'state': 'open', 'created_at': '2021-12-31T21:51:13Z', 'updated_at': '2022-02-21T04:42:32Z', 'due_on': '2022-06-30T07:00:00Z', 'closed_at': None}",0,2022-02-20T20:09:44Z,2022-02-21T02:30:19Z,,MEMBER,,"- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/v1.5.0.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46087/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46087/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46087', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46087', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46087.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46087.patch', 'merged_at': None}"
7,https://api.github.com/repos/pandas-dev/pandas/issues/46086,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46086/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46086/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46086/events,https://github.com/pandas-dev/pandas/pull/46086,1145111146,PR_kwDOAA0YD84zMaKJ,46086,BUG/REF: Use lru_cache instead of NUMBA_FUNC_CACHE,"{'login': 'mroeschke', 'id': 10647082, 'node_id': 'MDQ6VXNlcjEwNjQ3MDgy', 'avatar_url': 'https://avatars.githubusercontent.com/u/10647082?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mroeschke', 'html_url': 'https://github.com/mroeschke', 'followers_url': 'https://api.github.com/users/mroeschke/followers', 'following_url': 'https://api.github.com/users/mroeschke/following{/other_user}', 'gists_url': 'https://api.github.com/users/mroeschke/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mroeschke/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mroeschke/subscriptions', 'organizations_url': 'https://api.github.com/users/mroeschke/orgs', 'repos_url': 'https://api.github.com/users/mroeschke/repos', 'events_url': 'https://api.github.com/users/mroeschke/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mroeschke/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 2138993554, 'node_id': 'MDU6TGFiZWwyMTM4OTkzNTU0', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/numba', 'name': 'numba', 'color': '5319e7', 'default': False, 'description': 'numba-accelerated operations'}]",open,False,,[],,0,2022-02-20T19:23:09Z,2022-02-20T20:12:14Z,,MEMBER,,"- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/v1.5.0.rst` file if fixing a bug or adding a new feature.

","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46086/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46086/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46086', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46086', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46086.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46086.patch', 'merged_at': None}"
8,https://api.github.com/repos/pandas-dev/pandas/issues/46085,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46085/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46085/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46085/events,https://github.com/pandas-dev/pandas/issues/46085,1145040515,I_kwDOAA0YD85EP-6D,46085,BUG: read_sql_query returns different result type between m1 and intel processors,"{'login': 'kedarGil', 'id': 93583260, 'node_id': 'U_kgDOBZP3nA', 'avatar_url': 'https://avatars.githubusercontent.com/u/93583260?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/kedarGil', 'html_url': 'https://github.com/kedarGil', 'followers_url': 'https://api.github.com/users/kedarGil/followers', 'following_url': 'https://api.github.com/users/kedarGil/following{/other_user}', 'gists_url': 'https://api.github.com/users/kedarGil/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/kedarGil/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/kedarGil/subscriptions', 'organizations_url': 'https://api.github.com/users/kedarGil/orgs', 'repos_url': 'https://api.github.com/users/kedarGil/repos', 'events_url': 'https://api.github.com/users/kedarGil/events{/privacy}', 'received_events_url': 'https://api.github.com/users/kedarGil/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-02-20T14:48:07Z,2022-02-20T14:48:07Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd

ret_df = pd.read_sql_query(sql, self.connection, params=params)
```


### Issue Description

When upgrading to python 3.10.1 and pandas 1.4.1, many of our unit tests failed suddenly with the error:
AttributeError: 'str' object has no attribute 'get'

we are using the read_sql_query, and a field in the return value, that used to return as dict, suddenly returns as str, as if it is missing a json.loads() call.

The reason we need this version update is to support the new mac M1 computers that developers are getting.
HOWEVER, the wierd part, is that running this version on mac M1 , returns the expected results and tests are passing!

The environment is exactly the same as it was installed with pipfile.lock
We tested this on multiple computers, and always got the same results. As if the mac M1 processes differently / compiles different versions that produce valid results.



### Expected Behavior

return values are parsed and loaded as dict in dataframe - but in the intel computers upgraded to 1.4.1 and python 3.10.1 we recieve some parameters as strings(loading from the same query and the same raw data of course) which is inconsistent with previous version installed (pandas 1.2.5 and python 3.7.8)

### Installed Versions

<details>

Getting an error running show_versions() both on m1 and on intel. Attached is pip list

Package                    Version
-------------------------- ---------
adal                       1.2.7
ansimarkup                 1.5.0
appnope                    0.1.2
argon2-cffi                21.3.0
argon2-cffi-bindings       21.2.0
arnparse                   0.0.2
asn1crypto                 1.4.0
asttokens                  2.0.5
asyncpg                    0.25.0
attrs                      21.4.0
azure-core                 1.22.1
backcall                   0.2.0
black                      22.1.0
bleach                     4.1.0
boto3                      1.21.3
botocore                   1.24.3
cachetools                 5.0.0
cattrs                     1.6.0
certifi                    2021.10.8
cffi                       1.15.0
chardet                    3.0.4
charset-normalizer         2.0.12
click                      8.0.4
click-default-group        1.2.2
click-repl                 0.2.0
colorama                   0.4.4
cryptography               36.0.1
debugpy                    1.5.1
decorator                  5.1.1
deepmerge                  1.0.1
defusedxml                 0.7.1
dict2xml                   1.7.1
dill                       0.3.4
entrypoints                0.4
executing                  0.8.2
filelock                   3.6.0
Flask                      2.0.3
greenlet                   1.1.2
greynoise                  1.2.0
gunicorn                   20.1.0
idna                       2.5
importlib-metadata         1.7.0
iniconfig                  1.1.1
investigation-tools        1.0.94
ipdb                       0.13.9
ipykernel                  6.9.1
ipython                    8.0.1
ipython-genutils           0.2.0
ipywidgets                 7.6.5
isodate                    0.6.1
itsdangerous               2.1.0
jedi                       0.18.1
Jinja2                     3.0.3
jmespath                   0.10.0
jsonschema                 4.4.0
jupyter                    1.0.0
jupyter-client             7.1.2
jupyter-console            6.4.0
jupyter-core               4.9.2
jupyterlab-pygments        0.1.2
jupyterlab-widgets         1.0.2
lazy-object-proxy          1.7.1
MarkupSafe                 2.1.0
matplotlib-inline          0.1.3
mistune                    0.8.4
more-itertools             8.12.0
msrest                     0.6.21
msrestazure                0.6.4
mypy-extensions            0.4.3
nbclient                   0.5.11
nbconvert                  6.4.2
nbformat                   5.1.3
nest-asyncio               1.5.4
networkx                   2.6.3
notebook                   6.4.8
numpy                      1.22.2
oauthlib                   3.2.0
oscrypto                   1.2.1
packaging                  21.3
pandas                     1.4.1
pandocfilters              1.5.0
parso                      0.8.3
pathspec                   0.9.0
pexpect                    4.8.0
pickleshare                0.7.5
pip                        21.3.1
placeholder                1.1
platformdirs               2.5.0
pluggy                     1.0.0
prometheus-client          0.13.1
prometheus-flask-exporter  0.18.7
prompt-toolkit             3.0.28
psycopg2                   2.9.3
ptyprocess                 0.7.0
pure-eval                  0.2.2
py                         1.11.0
pycparser                  2.21
pycryptodomex              3.14.1
pyfunctional               1.4.3
Pygments                   2.11.2
PyJWT                      2.3.0
pyOpenSSL                  21.0.0
pyparsing                  3.0.7
pyrsistent                 0.18.1
pytest                     7.0.1
pytest-env                 0.6.2
python-dateutil            2.8.2
python-Levenshtein         0.12.2
pytz                       2021.3
PyYAML                     6.0
pyzmq                      22.3.0
qtconsole                  5.2.2
QtPy                       2.0.1
ratelimit                  2.2.1
requests                   2.27.1
requests-file              1.5.1
requests-oauthlib          1.3.1
retry                      0.9.2
ruamel.yaml                0.17.21
ruamel.yaml.clib           0.2.6
s3transfer                 0.5.1
Send2Trash                 1.8.0
sentry-sdk                 1.5.5
setuptools                 60.9.3
six                        1.16.0
snowflake-connector-python 2.7.4
snowflake-sqlalchemy       1.3.3
SQLAlchemy                 1.4.31
stack-data                 0.2.0
structlog                  21.5.0
tabulate                   0.8.9
tenacity                   6.3.1
terminado                  0.13.1
testpath                   0.5.0
timeout-decorator          0.5.0
tldextract                 3.1.2
toml                       0.10.2
tomli                      2.0.1
tornado                    6.1
traitlets                  5.1.1
typing_extensions          4.1.1
ua-parser                  0.10.0
urllib3                    1.26.8
user-agents                2.2.0
utils                      1.0.1
wcwidth                    0.2.5
webencodings               0.5.1
Werkzeug                   2.0.3
wheel                      0.37.1
widgetsnbextension         3.5.2
zipp                       3.7.0

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46085/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46085/timeline,,,
9,https://api.github.com/repos/pandas-dev/pandas/issues/46084,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46084/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46084/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46084/events,https://github.com/pandas-dev/pandas/issues/46084,1145009318,I_kwDOAA0YD85EP3Sm,46084,BUG: DataFrame.explode incomplete support on multiple columns,"{'login': 'ehariri', 'id': 21693509, 'node_id': 'MDQ6VXNlcjIxNjkzNTA5', 'avatar_url': 'https://avatars.githubusercontent.com/u/21693509?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ehariri', 'html_url': 'https://github.com/ehariri', 'followers_url': 'https://api.github.com/users/ehariri/followers', 'following_url': 'https://api.github.com/users/ehariri/following{/other_user}', 'gists_url': 'https://api.github.com/users/ehariri/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ehariri/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ehariri/subscriptions', 'organizations_url': 'https://api.github.com/users/ehariri/orgs', 'repos_url': 'https://api.github.com/users/ehariri/repos', 'events_url': 'https://api.github.com/users/ehariri/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ehariri/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-02-20T12:42:16Z,2022-02-20T12:53:36Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
import numpy as np

df = pd.DataFrame({""A"": [[0, 1], [5], [], [2, 3]],""B"": [9, 8, 7, 6],""C"": [[1, 2], np.nan, [], [3, 4]],})

df.explode([""A"", ""C""])
```


### Issue Description

The `DataFrame.explode` function has incomplete behavior for the above example when exploding on multiple columns. For the above DataFrame `df = pd.DataFrame({""A"": [[0, 1], [5], [], [2, 3]],""B"": [9, 8, 7, 6],""C"": [[1, 2], np.nan, [], [3, 4]],})` the outputs for exploding columns ""A"" and ""C"" individual are correctly outputted as
```python3
>>> df.explode(""A"")
     A  B       C
0    0  9  [1, 2]
0    1  9  [1, 2]
1    5  8     NaN
2  NaN  7      []
3    2  6  [3, 4]
3    3  6  [3, 4]

>>> df.explode(""C"")
        A  B    C
0  [0, 1]  9    1
0  [0, 1]  9    2
1     [5]  8  NaN
2      []  7  NaN
3  [2, 3]  6    3
3  [2, 3]  6    4
```
However, when attempting `df.explode([""A"", ""C""])`, one receives the error
```python3
>>> df.explode([""A"", ""C""])
Traceback (most recent call last):
  File ""<stdin>"", line 1, in <module>
  File ""/Users/emaanhariri/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py"", line 8254, in explode
    raise ValueError(""columns must have matching element counts"")
ValueError: columns must have matching element counts
```
Here the `mylen` function on line 8335 in the [explode function](https://github.com/pandas-dev/pandas/blob/v1.4.1/pandas/core/frame.py#L8221-L8348) is defined as `mylen = lambda x: len(x) if is_list_like(x) else -1` induces the error above as entries `[]` and `np.nan` are computed as having different lengths despite both ultimately occupying a single entry in the expansion. 

### Expected Behavior

We expect the output to be an appropriate mix between the output of `df.explode(""A"")` and `df.explode(""C"")` as follows.

```python3 
>>> df.explode([""A"", ""C""])
     A  B    C
0    0  1    1
0    1  1    2
1    5  7  NaN
2  NaN  2  NaN
3    3  4    1
3    4  4    2
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.8.12.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.3.0
Version          : Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.4
numpy            : 1.20.3
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : 0.29.24
pytest           : 6.2.5
hypothesis       : None
sphinx           : 4.4.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.7.1
html5lib         : None
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 3.0.2
IPython          : 7.29.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : None
fsspec           : 2021.11.1
fastparquet      : None
gcsfs            : 2021.11.1
matplotlib       : 3.4.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 5.0.0
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : 1.4.27
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : 0.55.0

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46084/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46084/timeline,,,
10,https://api.github.com/repos/pandas-dev/pandas/issues/46082,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46082/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46082/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46082/events,https://github.com/pandas-dev/pandas/issues/46082,1144981705,I_kwDOAA0YD85EPwjJ,46082,ENH: Make DataFrame.info() follow display.unicode.east_asian_width option,"{'login': 'dlimpid', 'id': 3257214, 'node_id': 'MDQ6VXNlcjMyNTcyMTQ=', 'avatar_url': 'https://avatars.githubusercontent.com/u/3257214?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/dlimpid', 'html_url': 'https://github.com/dlimpid', 'followers_url': 'https://api.github.com/users/dlimpid/followers', 'following_url': 'https://api.github.com/users/dlimpid/following{/other_user}', 'gists_url': 'https://api.github.com/users/dlimpid/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/dlimpid/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/dlimpid/subscriptions', 'organizations_url': 'https://api.github.com/users/dlimpid/orgs', 'repos_url': 'https://api.github.com/users/dlimpid/repos', 'events_url': 'https://api.github.com/users/dlimpid/events{/privacy}', 'received_events_url': 'https://api.github.com/users/dlimpid/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-02-20T10:38:14Z,2022-02-20T10:38:14Z,,NONE,,"If `display.unicode.east_asian_width` is enabled pandas aligns CJK characters properly, as width 2, when printing data frame or series.

It seems that, however, `DataFrame.info()` does not change its behavior.

Is it possible to make `DataFrame.info()` also follow the option?

```python
pd.set_option(""display.notebook_repr_html"", False)
pd.set_option(""display.unicode.east_asian_width"", True)

df = pd.DataFrame(
    {
        ""열이름"": [""하나"", ""둘"", ""셋""],
        ""列名"": [""いち"", ""に"", ""さん""],
        ""column"": [""one"", ""two"", ""three""],
    }
)
print(df)
print(df.dtypes)
df.info()
```

![image](https://user-images.githubusercontent.com/3257214/154838556-0ff50da8-6eec-4863-a51e-18e703eac690.png)
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46082/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46082/timeline,,,
11,https://api.github.com/repos/pandas-dev/pandas/issues/46081,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46081/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46081/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46081/events,https://github.com/pandas-dev/pandas/issues/46081,1144905859,I_kwDOAA0YD85EPeCD,46081,DOC: missing path-like at path parameter in to_pickle(),"{'login': 'simon-spier0', 'id': 60992048, 'node_id': 'MDQ6VXNlcjYwOTkyMDQ4', 'avatar_url': 'https://avatars.githubusercontent.com/u/60992048?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/simon-spier0', 'html_url': 'https://github.com/simon-spier0', 'followers_url': 'https://api.github.com/users/simon-spier0/followers', 'following_url': 'https://api.github.com/users/simon-spier0/following{/other_user}', 'gists_url': 'https://api.github.com/users/simon-spier0/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/simon-spier0/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/simon-spier0/subscriptions', 'organizations_url': 'https://api.github.com/users/simon-spier0/orgs', 'repos_url': 'https://api.github.com/users/simon-spier0/repos', 'events_url': 'https://api.github.com/users/simon-spier0/events{/privacy}', 'received_events_url': 'https://api.github.com/users/simon-spier0/received_events', 'type': 'User', 'site_admin': False}","[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs', 'name': 'Docs', 'color': '3465A4', 'default': False, 'description': None}, {'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMjgwOTg4NDI3', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Typing', 'name': 'Typing', 'color': 'ea91a4', 'default': False, 'description': 'type annotations, mypy/pyright type checking'}]",open,False,"{'login': 'marco-georgaklis', 'id': 51515552, 'node_id': 'MDQ6VXNlcjUxNTE1NTUy', 'avatar_url': 'https://avatars.githubusercontent.com/u/51515552?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/marco-georgaklis', 'html_url': 'https://github.com/marco-georgaklis', 'followers_url': 'https://api.github.com/users/marco-georgaklis/followers', 'following_url': 'https://api.github.com/users/marco-georgaklis/following{/other_user}', 'gists_url': 'https://api.github.com/users/marco-georgaklis/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/marco-georgaklis/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/marco-georgaklis/subscriptions', 'organizations_url': 'https://api.github.com/users/marco-georgaklis/orgs', 'repos_url': 'https://api.github.com/users/marco-georgaklis/repos', 'events_url': 'https://api.github.com/users/marco-georgaklis/events{/privacy}', 'received_events_url': 'https://api.github.com/users/marco-georgaklis/received_events', 'type': 'User', 'site_admin': False}","[{'login': 'marco-georgaklis', 'id': 51515552, 'node_id': 'MDQ6VXNlcjUxNTE1NTUy', 'avatar_url': 'https://avatars.githubusercontent.com/u/51515552?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/marco-georgaklis', 'html_url': 'https://github.com/marco-georgaklis', 'followers_url': 'https://api.github.com/users/marco-georgaklis/followers', 'following_url': 'https://api.github.com/users/marco-georgaklis/following{/other_user}', 'gists_url': 'https://api.github.com/users/marco-georgaklis/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/marco-georgaklis/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/marco-georgaklis/subscriptions', 'organizations_url': 'https://api.github.com/users/marco-georgaklis/orgs', 'repos_url': 'https://api.github.com/users/marco-georgaklis/repos', 'events_url': 'https://api.github.com/users/marco-georgaklis/events{/privacy}', 'received_events_url': 'https://api.github.com/users/marco-georgaklis/received_events', 'type': 'User', 'site_admin': False}]","{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/32', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32/labels', 'id': 933188, 'node_id': 'MDk6TWlsZXN0b25lOTMzMTg4', 'number': 32, 'title': 'Contributions Welcome', 'description': 'Changes that would be nice to have in the next release. These issues are not blocking. They will be pushed to the next release if no one has time to fix them.', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 993, 'closed_issues': 832, 'state': 'open', 'created_at': '2015-01-13T10:53:19Z', 'updated_at': '2022-02-20T22:03:14Z', 'due_on': None, 'closed_at': None}",2,2022-02-20T03:09:58Z,2022-02-20T23:43:20Z,,NONE,,"### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)


### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.to_pickle.html

### Documentation problem

Based on documentation, it accepts parameter path as str. Inside the to_pickle(), the path parameter is put to stringify_path() so it accepts path-like object actually.

### Suggested fix for documentation

Adding path-like object to documentation removes warning in PyCharm.
![image](https://user-images.githubusercontent.com/60992048/154826832-3f9a70f3-3c29-4f1b-8b78-c74901e33a3c.png)
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46081/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46081/timeline,,,
12,https://api.github.com/repos/pandas-dev/pandas/issues/46080,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46080/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46080/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46080/events,https://github.com/pandas-dev/pandas/pull/46080,1144901980,PR_kwDOAA0YD84zLzVP,46080,Typeinterval part1,"{'login': 'Dr-Irv', 'id': 15113894, 'node_id': 'MDQ6VXNlcjE1MTEzODk0', 'avatar_url': 'https://avatars.githubusercontent.com/u/15113894?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Dr-Irv', 'html_url': 'https://github.com/Dr-Irv', 'followers_url': 'https://api.github.com/users/Dr-Irv/followers', 'following_url': 'https://api.github.com/users/Dr-Irv/following{/other_user}', 'gists_url': 'https://api.github.com/users/Dr-Irv/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Dr-Irv/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Dr-Irv/subscriptions', 'organizations_url': 'https://api.github.com/users/Dr-Irv/orgs', 'repos_url': 'https://api.github.com/users/Dr-Irv/repos', 'events_url': 'https://api.github.com/users/Dr-Irv/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Dr-Irv/received_events', 'type': 'User', 'site_admin': False}","[{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMjgwOTg4NDI3', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Typing', 'name': 'Typing', 'color': 'ea91a4', 'default': False, 'description': 'type annotations, mypy/pyright type checking'}]",open,False,,[],,5,2022-02-20T02:42:44Z,2022-02-21T11:09:55Z,,CONTRIBUTOR,,"I would like to add `pandas/_libs/interval.pyi`,  and I have a tentative file for that, but when I started to do that, it uncovered issues in our existing typing, because currently, `mypy` sees `Interval` as `Unknown`, which allows a bunch of things to pass.

So this PR addresses that issue.  The way to see the problems that were fixed by this PR is to change in `_typing.pyi`:
```python
PandasScalar = Union[""Period"", ""Timestamp"", ""Timedelta"", ""Interval""]
```
TO
```python
PandasScalar = Union[""Period"", ""Timestamp"", ""Timedelta""]  # , ""Interval""]
```

A followup PR will add `pandas/_libs/interval.pyi` and make changes to handle that.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46080/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46080/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46080', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46080', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46080.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46080.patch', 'merged_at': None}"
13,https://api.github.com/repos/pandas-dev/pandas/issues/46079,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46079/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46079/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46079/events,https://github.com/pandas-dev/pandas/issues/46079,1144874270,I_kwDOAA0YD85EPWUe,46079,DOC: tail works even if n > length of DataFrame,"{'login': 'kevinlinxc', 'id': 44324811, 'node_id': 'MDQ6VXNlcjQ0MzI0ODEx', 'avatar_url': 'https://avatars.githubusercontent.com/u/44324811?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/kevinlinxc', 'html_url': 'https://github.com/kevinlinxc', 'followers_url': 'https://api.github.com/users/kevinlinxc/followers', 'following_url': 'https://api.github.com/users/kevinlinxc/following{/other_user}', 'gists_url': 'https://api.github.com/users/kevinlinxc/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/kevinlinxc/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/kevinlinxc/subscriptions', 'organizations_url': 'https://api.github.com/users/kevinlinxc/orgs', 'repos_url': 'https://api.github.com/users/kevinlinxc/repos', 'events_url': 'https://api.github.com/users/kevinlinxc/events{/privacy}', 'received_events_url': 'https://api.github.com/users/kevinlinxc/received_events', 'type': 'User', 'site_admin': False}","[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs', 'name': 'Docs', 'color': '3465A4', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,2,2022-02-19T23:46:12Z,2022-02-20T19:59:38Z,,NONE,,"### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)


### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.tail.html

### Documentation problem

It may be obvious to some, but if the `n` requested by `tail()` is greater than the length of the DataFrame, you get the entire DataFrame and no errors are thrown, and this is not mentioned in the documentation. This is useful for me because I'm trying to plot only the last 70 data points of a dataframe but the dataframe might not have 70 values yet. I think it would be reasonable to assume that one implementation would throw an out-of-bounds style exception. 

### Suggested fix for documentation

Add one line about how n > dataframe length is handled.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46079/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46079/timeline,,,
14,https://api.github.com/repos/pandas-dev/pandas/issues/46077,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46077/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46077/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46077/events,https://github.com/pandas-dev/pandas/issues/46077,1144844617,I_kwDOAA0YD85EPPFJ,46077,BUG: pytables.BinOp.prune passing str to BinOp constructor,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-02-19T20:57:56Z,2022-02-19T20:58:07Z,,MEMBER,,"computation.ops.BinOp docstring says that lhs and rhs should both be Term or Op objects.  Enforcing this breaks a bunch of tests bc strings are passed to the constructors in pytables.BinOp.prune.

If we could actually rely on having lhs and rhs both be Term | Op, then we could rule out the ndarray case in BinOp.conform.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46077/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46077/timeline,,,
15,https://api.github.com/repos/pandas-dev/pandas/issues/46075,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46075/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46075/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46075/events,https://github.com/pandas-dev/pandas/pull/46075,1144838614,PR_kwDOAA0YD84zLnyp,46075,ENH: Updated read_html to add option,"{'login': 'RomainL972', 'id': 24463530, 'node_id': 'MDQ6VXNlcjI0NDYzNTMw', 'avatar_url': 'https://avatars.githubusercontent.com/u/24463530?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/RomainL972', 'html_url': 'https://github.com/RomainL972', 'followers_url': 'https://api.github.com/users/RomainL972/followers', 'following_url': 'https://api.github.com/users/RomainL972/following{/other_user}', 'gists_url': 'https://api.github.com/users/RomainL972/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/RomainL972/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/RomainL972/subscriptions', 'organizations_url': 'https://api.github.com/users/RomainL972/orgs', 'repos_url': 'https://api.github.com/users/RomainL972/repos', 'events_url': 'https://api.github.com/users/RomainL972/events{/privacy}', 'received_events_url': 'https://api.github.com/users/RomainL972/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-02-19T20:26:33Z,2022-02-20T18:09:43Z,,NONE,,"- [x] closes #24766
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46075/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46075/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46075', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46075', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46075.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46075.patch', 'merged_at': None}"
16,https://api.github.com/repos/pandas-dev/pandas/issues/46074,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46074/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46074/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46074/events,https://github.com/pandas-dev/pandas/pull/46074,1144817476,PR_kwDOAA0YD84zLj7y,46074,"BUG: .transform(...) with ""first"" and ""last"" fail when axis=1","{'login': 'rhshadrach', 'id': 45562402, 'node_id': 'MDQ6VXNlcjQ1NTYyNDAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/45562402?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/rhshadrach', 'html_url': 'https://github.com/rhshadrach', 'followers_url': 'https://api.github.com/users/rhshadrach/followers', 'following_url': 'https://api.github.com/users/rhshadrach/following{/other_user}', 'gists_url': 'https://api.github.com/users/rhshadrach/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/rhshadrach/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/rhshadrach/subscriptions', 'organizations_url': 'https://api.github.com/users/rhshadrach/orgs', 'repos_url': 'https://api.github.com/users/rhshadrach/repos', 'events_url': 'https://api.github.com/users/rhshadrach/events{/privacy}', 'received_events_url': 'https://api.github.com/users/rhshadrach/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNjA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Groupby', 'name': 'Groupby', 'color': '729FCF', 'default': False, 'description': None}, {'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1MzEx', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Performance', 'name': 'Performance', 'color': 'a10c02', 'default': False, 'description': 'Memory or execution speed performance'}, {'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTEwMjk1MzU=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Clean', 'name': 'Clean', 'color': '207de5', 'default': False, 'description': None}, {'id': 2365523662, 'node_id': 'MDU6TGFiZWwyMzY1NTIzNjYy', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Nuisance%20Columns', 'name': 'Nuisance Columns', 'color': '120491', 'default': False, 'description': 'Identifying/Dropping nuisance columns in reductions, groupby.add, DataFrame.apply'}]",open,False,,[],,0,2022-02-19T18:43:50Z,2022-02-19T18:48:07Z,,MEMBER,,"Part of #45986 (first/last)

- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

This removes warnings of dropping nuisance columns when using e.g. `.transform(""mean"")`. This makes it consistent with `.agg`, and in #46072 both `transform` and `agg` will warn about the default switching from `numeric_only=False` to `numeric_only=True`. Doing this first will make #46072 slightly easier.

Not falling back to `_transform_item_by_item` is also better for performance. For the benchmark, I disabled the warning being emitted in main to make sure that wasn't messing up the results.

```
size = 1_000_000
df = pd.DataFrame(
    {
        ""A"": size * [""foo"", ""bar""],
        ""B"": ""one"",
        ""C"": np.random.randn(2*size),
        ""D"": np.random.randn(2*size),
    }
)
%timeit df.groupby(""A"").transform(""mean"")

# This PR
108 ms ± 966 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
# main, but with size set to 100_000 (1mm was taking very very long)
920 ms ± 7.95 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46074/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46074/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46074', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46074', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46074.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46074.patch', 'merged_at': None}"
17,https://api.github.com/repos/pandas-dev/pandas/issues/46072,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46072/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46072/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46072/events,https://github.com/pandas-dev/pandas/issues/46072,1144777104,I_kwDOAA0YD85EO-mQ,46072,DEPR: DataFrameGroupBy numeric_only defaulting to True,"{'login': 'rhshadrach', 'id': 45562402, 'node_id': 'MDQ6VXNlcjQ1NTYyNDAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/45562402?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/rhshadrach', 'html_url': 'https://github.com/rhshadrach', 'followers_url': 'https://api.github.com/users/rhshadrach/followers', 'following_url': 'https://api.github.com/users/rhshadrach/following{/other_user}', 'gists_url': 'https://api.github.com/users/rhshadrach/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/rhshadrach/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/rhshadrach/subscriptions', 'organizations_url': 'https://api.github.com/users/rhshadrach/orgs', 'repos_url': 'https://api.github.com/users/rhshadrach/repos', 'events_url': 'https://api.github.com/users/rhshadrach/events{/privacy}', 'received_events_url': 'https://api.github.com/users/rhshadrach/received_events', 'type': 'User', 'site_admin': False}","[{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNjA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Groupby', 'name': 'Groupby', 'color': '729FCF', 'default': False, 'description': None}, {'id': 87485152, 'node_id': 'MDU6TGFiZWw4NzQ4NTE1Mg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Deprecate', 'name': 'Deprecate', 'color': '5319e7', 'default': False, 'description': 'Functionality to remove in pandas'}, {'id': 2365523662, 'node_id': 'MDU6TGFiZWwyMzY1NTIzNjYy', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Nuisance%20Columns', 'name': 'Nuisance Columns', 'color': '120491', 'default': False, 'description': 'Identifying/Dropping nuisance columns in reductions, groupby.add, DataFrame.apply'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/92', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92/labels', 'id': 7530006, 'node_id': 'MI_kwDOAA0YD84AcuYW', 'number': 92, 'title': '1.5', 'description': '', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 37, 'closed_issues': 343, 'state': 'open', 'created_at': '2021-12-31T21:51:13Z', 'updated_at': '2022-02-21T04:42:32Z', 'due_on': '2022-06-30T07:00:00Z', 'closed_at': None}",2,2022-02-19T16:30:13Z,2022-02-19T18:53:09Z,,MEMBER,,"### Context

A summary of this behavior and the consensus thus far that DataFrameGroupBy will have `numeric_only` default to False in 2.0  can be found here: https://github.com/pandas-dev/pandas/issues/42395#issuecomment-908690066. 

In #41475, the silent dropping of nuisance columns was deprecated.

In #43154, the behavior was changed so that when a DataFrame has `numeric_only` unspecified and subsetting to numeric only columns would leave the DataFrame empty, internally pandas treats `numeric_only` as `False`.

Even though there is consensus that `numeric_only` should default to False, because of the above changes I wanted to make sure there is a consensus on how to go about doing so before proceeding.

For the discussion below, it is useful to have three types of columns in mind:

 - Numeric: Columns that remain in the input when `numeric_only=True`.
 - Nonnumeric, can agg: Columns that do not remain in the input when `numeric_only=True` but can still be successfully aggregated; e.g. strings with `sum`.
 - Nonnumeric, can't agg: Columns that do not remain in the input when `numeric_only=True` and cannot be successfully aggregated; e.g. `object`.

### Code

To investigate this on 1.4.x, I have been using the following code. In this code, I am using `.sum()`. However the results for any reduction or transform, whether it be string or callable, should have the same behavior (though that is not the case today). This includes apply and using axis=1 (for which you may want to tilt your head 90 degrees to the left).

<details>
<summary>Code</summary>

```
numeric = [1, 1]
nonnumeric_noagg = [object, object]
nonnumeric_agg = [""2"", ""2""]
for has_numeric, has_nonnumeric_agg, has_nonnumeric_noagg in it.product([True, False], repeat=3):
    for numeric_only in [True, False, lib.no_default]:
        print(has_numeric, has_nonnumeric_agg, has_nonnumeric_noagg, numeric_only)
        df = pd.DataFrame({""A"": [1, 1]})
        if has_numeric:
            df[""B""] = numeric
        if has_nonnumeric_agg:
            df[""C""] = nonnumeric_agg
        if has_nonnumeric_noagg:
            df[""D""] = nonnumeric_noagg
        warning_msg = """"
        try:
            with warnings.catch_warnings(record=True) as w:
                result = df.groupby(""A"").sum(numeric_only=numeric_only)
                if len(w) > 0:
                    assert len(w) == 1
                    assert issubclass(w[-1].category, FutureWarning)
                    warning_msg = str(w[-1].message)
        except TypeError:
            print(""  TypeError"")
        else:
            print(""  Columns:"", result.columns.tolist(), ""Warning:"", warning_msg[:20])
```

</details>

### Current and Future behavior

#### `numeric_only=True`

Current behavior appears entirely correct and will go unchanged in 1.5/2.0. In particular, when there are no numeric columns in the input, the output is empty as well.

#### `numeric_only=False`

Current behavior appears entirely correct, in that if there are to be any behavior changes in 2.0, we already emit the appropriate FutureWarning today. The only case where there will be a behavior change from 1.4.x to 2.0 is if the frame contains a nonnumeric column that can't be aggregated. 1.4.x drops the column whereas 2.0 will raise a TypeError.

#### `numeric_only` unspecified (`lib.no_default`)

I'll refer to the columns as in the code above:

 - B: Numeric column
 - C: Nonnumeric column that can be aggregated
 - D: Nonnumeric column that cannot be aggregated

1. Columns `['B', 'C', 'D']`

    - In 1.4.x we get column B and no warning is raised. In 2.0 this will raise a TypeError.
    - We should emit a warning in 1.5 about `numeric_only` defaulting to False in 2.0.

2. Columns `['B', 'C']`

    - In 1.4.x we get column B and no warning is raised. In 2.0 will we get both B and C in the result.
    - We should emit a warning in 1.5 about `numeric_only` defaulting to False in 2.0.

3. Columns `['B', 'D']`

    - In 1.4.x we get column B and no warning is raised. In 2.0 we will raise a TypeError.
    - We should emit a warning in 1.5 about `numeric_only` defaulting to False in 2.0.

4. Columns `['C', 'D']`

    - In 2.0 we will raise a TypeError, and 1.4.x currently warns that this will happen.
    - No change.

5. Columns `['C']`

    - In 1.4.x we get column C and no warning is raised. This is the correct result on 2.0, but in my opinion is not the correct result on 1.4.x where we should be treating `numeric_only` as True.
    - No change. It is not worth it to change behavior and raise a FutureWarning that the behavior will go back to what it is now.

6. Columns `['D']`

    - On 1.4.x this returns an empty result and warns that it will raise a TypeError. In 2.0, it will raise a TypeError.
    - No change.

cc @jreback @jbrockmendel @jorisvandenbossche @simonjayhawkins @Dr-Irv ","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46072/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46072/timeline,,,
18,https://api.github.com/repos/pandas-dev/pandas/issues/46071,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46071/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46071/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46071/events,https://github.com/pandas-dev/pandas/issues/46071,1144728963,I_kwDOAA0YD85EOy2D,46071,BUG: to_datetime does not raise when errors='raise'.,"{'login': 'gitgithan', 'id': 29853829, 'node_id': 'MDQ6VXNlcjI5ODUzODI5', 'avatar_url': 'https://avatars.githubusercontent.com/u/29853829?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/gitgithan', 'html_url': 'https://github.com/gitgithan', 'followers_url': 'https://api.github.com/users/gitgithan/followers', 'following_url': 'https://api.github.com/users/gitgithan/following{/other_user}', 'gists_url': 'https://api.github.com/users/gitgithan/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/gitgithan/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/gitgithan/subscriptions', 'organizations_url': 'https://api.github.com/users/gitgithan/orgs', 'repos_url': 'https://api.github.com/users/gitgithan/repos', 'events_url': 'https://api.github.com/users/gitgithan/events{/privacy}', 'received_events_url': 'https://api.github.com/users/gitgithan/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-02-19T14:31:46Z,2022-02-19T14:31:46Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd

s = pd.Series(['6/30/2025','1 27 2024'])
pd.to_datetime(s,errors='raise',infer_datetime_format=True)
```


### Issue Description

I'm confused about the interaction between `errors = {raise, coerce}` and `infer_datetime_format = {True, False}`.

1. From experiment 3, it tells me if I want to follow the format in first row using infer=True, the second row has a problem which causes it to be coerced to NaT. 

2. I also understand that in experiment 4, because infer=False, each row is free to have it's own format not necessarily following the format inferred from first row, so it doesn't have any problem being converted, thus not NaT.

3. **I don't understand why experiment 1 does not raise any error but converts row 2 properly?** 
(From experiment 3 i expect row 2 to be problematic when infer=True)

4. I understand experiment 2 converts with no problem because infer=False allows every row to have it's own format, similar reasoning as for experiment 4.


I tried 4 experiments on the same series of `s = pd.Series(['6/30/2025','1 27 2024'])`

**Experiment 1. errors = 'raise', infer_datetime_format=True**

**Input:** `pd.to_datetime(s,errors='raise',infer_datetime_format=True)`
**Output:**
```
0   2025-06-30
1   2024-01-27
dtype: datetime64[ns]
```

**Experiment 2. errors = 'raise', infer_datetime_format=False**

**Input:** `pd.to_datetime(s,errors='raise',infer_datetime_format=False)`
**Output: Same as experiment 1**

**Experiment 3. errors = 'coerce', infer_datetime_format=True** 

**Input:** `pd.to_datetime(s,errors='coerce',infer_datetime_format=True)`
**Output:**

```
0   2025-06-30
1          NaT
dtype: datetime64[ns]
```
**Experiment 4. errors = 'coerce', infer_datetime_format=False**

**Input:** `pd.to_datetime(s,errors='coerce',infer_datetime_format=False)`
**Output: Same as experiment 1**


### Expected Behavior

I expect the same error that caused experiment 3 to produce NaT in 2nd row with `'1 27 2024'`, to generate some error in experiment 1 for 2nd row too. 
I'm not sure what caused the NaT in experiment 3, but reasoning from the assumption that if `errors='coerce'` has found some problem, `errors='raise'` should find that problem too.
I also assume the NaT in experiment 3 is caused by infer_datetime_format by comparing experiment 3 and 4.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.8.12.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.4.0
Version          : Darwin Kernel Version 20.4.0: Fri Mar  5 01:14:14 PST 2021; root:xnu-7195.101.1~3/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.0
numpy            : 1.21.4
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.1.1
setuptools       : 56.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.4
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 7.30.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.0
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : 1.4.29
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : 2.0.1
xlwt             : None
zstandard        : None

</details>","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46071/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46071/timeline,,,
19,https://api.github.com/repos/pandas-dev/pandas/issues/46068,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46068/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46068/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46068/events,https://github.com/pandas-dev/pandas/pull/46068,1144658934,PR_kwDOAA0YD84zLDgQ,46068,Construction of series with na and datetime dtype,"{'login': 'weikhor', 'id': 36619387, 'node_id': 'MDQ6VXNlcjM2NjE5Mzg3', 'avatar_url': 'https://avatars.githubusercontent.com/u/36619387?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/weikhor', 'html_url': 'https://github.com/weikhor', 'followers_url': 'https://api.github.com/users/weikhor/followers', 'following_url': 'https://api.github.com/users/weikhor/following{/other_user}', 'gists_url': 'https://api.github.com/users/weikhor/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/weikhor/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/weikhor/subscriptions', 'organizations_url': 'https://api.github.com/users/weikhor/orgs', 'repos_url': 'https://api.github.com/users/weikhor/repos', 'events_url': 'https://api.github.com/users/weikhor/events{/privacy}', 'received_events_url': 'https://api.github.com/users/weikhor/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,1,2022-02-19T11:02:17Z,2022-02-20T04:58:18Z,,CONTRIBUTOR,,"- [✓] closes #41805 
- [✓] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [✓] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46068/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46068/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46068', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46068', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46068.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46068.patch', 'merged_at': None}"
20,https://api.github.com/repos/pandas-dev/pandas/issues/46067,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46067/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46067/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46067/events,https://github.com/pandas-dev/pandas/issues/46067,1144384928,I_kwDOAA0YD85ENe2g,46067,BUG: incorrect spacing with 'background-color' and Styler.to_latex(convert_css=True),"{'login': 'andreostrovsky', 'id': 18727813, 'node_id': 'MDQ6VXNlcjE4NzI3ODEz', 'avatar_url': 'https://avatars.githubusercontent.com/u/18727813?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/andreostrovsky', 'html_url': 'https://github.com/andreostrovsky', 'followers_url': 'https://api.github.com/users/andreostrovsky/followers', 'following_url': 'https://api.github.com/users/andreostrovsky/following{/other_user}', 'gists_url': 'https://api.github.com/users/andreostrovsky/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/andreostrovsky/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/andreostrovsky/subscriptions', 'organizations_url': 'https://api.github.com/users/andreostrovsky/orgs', 'repos_url': 'https://api.github.com/users/andreostrovsky/repos', 'events_url': 'https://api.github.com/users/andreostrovsky/events{/privacy}', 'received_events_url': 'https://api.github.com/users/andreostrovsky/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 251382258, 'node_id': 'MDU6TGFiZWwyNTEzODIyNTg=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20LaTeX', 'name': 'IO LaTeX', 'color': '006b75', 'default': False, 'description': 'to_latex'}, {'id': 307649777, 'node_id': 'MDU6TGFiZWwzMDc2NDk3Nzc=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Info', 'name': 'Needs Info', 'color': '207de5', 'default': False, 'description': 'Clarification about behavior needed to assess issue'}, {'id': 1728592794, 'node_id': 'MDU6TGFiZWwxNzI4NTkyNzk0', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Styler', 'name': 'Styler', 'color': '006b75', 'default': False, 'description': 'conditional formatting using DataFrame.style'}]",open,False,,[],,1,2022-02-19T05:05:03Z,2022-02-19T06:54:42Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame([range(5), range(5), range(5)])
print(pd.style.set_properties(subset=pd.IndexSlice[1,:], **{'background-color':'#F5E3E8'}).to_latex(convert_css=True))

produces:

\begin{tabular}{lrrrrr}
 & 0 & 1 & 2 & 3 & 4 \\
0 & 0 & 1 & 2 & 3 & 4 \\
1 & {\cellcolor[HTML]{F5E3E8}} 0 & {\cellcolor[HTML]{F5E3E8}} 1 & {\cellcolor[HTML]{F5E3E8}} 2 & {\cellcolor[HTML]{F5E3E8}} 3 & {\cellcolor[HTML]{F5E3E8}} 4 \\
2 & 0 & 1 & 2 & 3 & 4 \\
\end{tabular}
```


### Issue Description

As can be seen here: [https://tex.stackexchange.com/questions/205223/cellcolor-affects-horizontal-alignment-in-table](https://tex.stackexchange.com/questions/205223/cellcolor-affects-horizontal-alignment-in-table),
the latex command `\cellcolor` must not have a space between it and the cell contents.
When using `Styler.to_latex(convert_css=True)` to convert the CSS attribute `backgound-color` to `\cellcolor`, a space is inserted between the latex command and the cell contents causing horizontal misalignment.

### Expected Behavior

The expected behavior of the above example should produce:

\begin{tabular}{lrrrrr}
 & 0 & 1 & 2 & 3 & 4 \\
0 & 0 & 1 & 2 & 3 & 4 \\
1 & {\cellcolor[HTML]{F5E3E8}}0 & {\cellcolor[HTML]{F5E3E8}}1 & {\cellcolor[HTML]{F5E3E8}}2 & {\cellcolor[HTML]{F5E3E8}}3 & {\cellcolor[HTML]{F5E3E8}}4 \\
2 & 0 & 1 & 2 & 3 & 4 \\
\end{tabular}

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.9.9.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19042
machine          : AMD64
processor        : Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.4.0
numpy            : 1.22.1
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 60.5.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.0.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 6.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : 1.4.31
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46067/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46067/timeline,,,
21,https://api.github.com/repos/pandas-dev/pandas/issues/46066,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46066/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46066/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46066/events,https://github.com/pandas-dev/pandas/issues/46066,1144196191,I_kwDOAA0YD85EMwxf,46066,PERF: dataframe.resample is very slowly in ver 1.4 and 1.4.1,"{'login': 'dovsay', 'id': 36002974, 'node_id': 'MDQ6VXNlcjM2MDAyOTc0', 'avatar_url': 'https://avatars.githubusercontent.com/u/36002974?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/dovsay', 'html_url': 'https://github.com/dovsay', 'followers_url': 'https://api.github.com/users/dovsay/followers', 'following_url': 'https://api.github.com/users/dovsay/following{/other_user}', 'gists_url': 'https://api.github.com/users/dovsay/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/dovsay/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/dovsay/subscriptions', 'organizations_url': 'https://api.github.com/users/dovsay/orgs', 'repos_url': 'https://api.github.com/users/dovsay/repos', 'events_url': 'https://api.github.com/users/dovsay/events{/privacy}', 'received_events_url': 'https://api.github.com/users/dovsay/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1MzEx', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Performance', 'name': 'Performance', 'color': 'a10c02', 'default': False, 'description': 'Memory or execution speed performance'}, {'id': 13098779, 'node_id': 'MDU6TGFiZWwxMzA5ODc3OQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Reshaping', 'name': 'Reshaping', 'color': '02d7e1', 'default': False, 'description': 'Concat, Merge/Join, Stack/Unstack, Explode'}, {'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQwNDUyMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Dtype%20Conversions', 'name': 'Dtype Conversions', 'color': 'e102d8', 'default': False, 'description': 'Unexpected or buggy dtype conversions'}, {'id': 32815646, 'node_id': 'MDU6TGFiZWwzMjgxNTY0Ng==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Regression', 'name': 'Regression', 'color': 'e11d21', 'default': False, 'description': 'Functionality that used to work in a prior pandas version'}]",open,False,,[],,3,2022-02-19T02:38:00Z,2022-02-20T14:17:30Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this issue exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this issue exists on the main branch of pandas.


### Reproducible Example

    df_con = df_con.reindex(columns = ['datetime','open','high','low','close','volume','amount'])
    ##    重新采样——5 to 15
    
    df_con.drop(columns=['amount'],inplace=True)
    df_con.set_index('datetime',inplace=True)
    ohlc_dict = {                                                                                                             
            'open':'first',                                                                                                    
            'high':'max',                                                                                                       
            'low':'min',                                                                                                        
            'close': 'last',                                                                                                    
            'volume': 'sum'
            }
    o =time.time()
    df_con = df_con.resample('15min',closed='right', label='right').apply(ohlc_dict)
    print(time.time() - o)

#----------------------
# df_con  the dataframe read from the csv file includes 14690 rows
# codes print 8.608731031417847 （about 9 seconds on average）


### Installed Versions

<details>


INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.9.10.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : zh_CN
LOCALE           : Chinese (Simplified)_China.936

pandas           : 1.4.1
numpy            : 1.22.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 22.0.3
setuptools       : 60.9.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : 4.4.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 7.31.1
pandas_datareader: None
bs4              : None
bottleneck       : 1.3.2
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
None
</details>


### Prior Performance

same code as above
It prints 0.015625476837158203（about 0.015 seconds on average）,when i change the version to 1.3.5
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46066/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46066/timeline,,,
22,https://api.github.com/repos/pandas-dev/pandas/issues/46064,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46064/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46064/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46064/events,https://github.com/pandas-dev/pandas/pull/46064,1143883713,PR_kwDOAA0YD84zIOav,46064,DOC: added examples for index assignment using Series,"{'login': 'marco-georgaklis', 'id': 51515552, 'node_id': 'MDQ6VXNlcjUxNTE1NTUy', 'avatar_url': 'https://avatars.githubusercontent.com/u/51515552?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/marco-georgaklis', 'html_url': 'https://github.com/marco-georgaklis', 'followers_url': 'https://api.github.com/users/marco-georgaklis/followers', 'following_url': 'https://api.github.com/users/marco-georgaklis/following{/other_user}', 'gists_url': 'https://api.github.com/users/marco-georgaklis/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/marco-georgaklis/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/marco-georgaklis/subscriptions', 'organizations_url': 'https://api.github.com/users/marco-georgaklis/orgs', 'repos_url': 'https://api.github.com/users/marco-georgaklis/repos', 'events_url': 'https://api.github.com/users/marco-georgaklis/events{/privacy}', 'received_events_url': 'https://api.github.com/users/marco-georgaklis/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-02-18T22:44:22Z,2022-02-18T22:44:22Z,,NONE,,"- [x] closes #39845
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46064/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46064/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46064', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46064', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46064.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46064.patch', 'merged_at': None}"
23,https://api.github.com/repos/pandas-dev/pandas/issues/46063,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46063/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46063/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46063/events,https://github.com/pandas-dev/pandas/pull/46063,1143797205,PR_kwDOAA0YD84zH6xA,46063,BUG: BooleanArray match non-masked behavior div/pow/mod,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-02-18T21:28:21Z,2022-02-19T02:58:16Z,,MEMBER,,"- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46063/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46063/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46063', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46063', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46063.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46063.patch', 'merged_at': None}"
24,https://api.github.com/repos/pandas-dev/pandas/issues/46061,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46061/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46061/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46061/events,https://github.com/pandas-dev/pandas/issues/46061,1143734355,I_kwDOAA0YD85ELABT,46061,"BUG: groupby().rolling(""freq"") validation raises even if dates are sorted within each group","{'login': 'JILPulvino', 'id': 73976324, 'node_id': 'MDQ6VXNlcjczOTc2MzI0', 'avatar_url': 'https://avatars.githubusercontent.com/u/73976324?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/JILPulvino', 'html_url': 'https://github.com/JILPulvino', 'followers_url': 'https://api.github.com/users/JILPulvino/followers', 'following_url': 'https://api.github.com/users/JILPulvino/following{/other_user}', 'gists_url': 'https://api.github.com/users/JILPulvino/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/JILPulvino/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/JILPulvino/subscriptions', 'organizations_url': 'https://api.github.com/users/JILPulvino/orgs', 'repos_url': 'https://api.github.com/users/JILPulvino/repos', 'events_url': 'https://api.github.com/users/JILPulvino/events{/privacy}', 'received_events_url': 'https://api.github.com/users/JILPulvino/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNjA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Groupby', 'name': 'Groupby', 'color': '729FCF', 'default': False, 'description': None}, {'id': 32815646, 'node_id': 'MDU6TGFiZWwzMjgxNTY0Ng==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Regression', 'name': 'Regression', 'color': 'e11d21', 'default': False, 'description': 'Functionality that used to work in a prior pandas version'}, {'id': 1045950827, 'node_id': 'MDU6TGFiZWwxMDQ1OTUwODI3', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Window', 'name': 'Window', 'color': 'd4c5f9', 'default': False, 'description': 'rolling, ewma, expanding'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/94', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/94', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/94/labels', 'id': 7667127, 'node_id': 'MI_kwDOAA0YD84AdP23', 'number': 94, 'title': '1.4.2', 'description': 'on-merge: backport to 1.4.x', 'creator': {'login': 'simonjayhawkins', 'id': 13159005, 'node_id': 'MDQ6VXNlcjEzMTU5MDA1', 'avatar_url': 'https://avatars.githubusercontent.com/u/13159005?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/simonjayhawkins', 'html_url': 'https://github.com/simonjayhawkins', 'followers_url': 'https://api.github.com/users/simonjayhawkins/followers', 'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}', 'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions', 'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs', 'repos_url': 'https://api.github.com/users/simonjayhawkins/repos', 'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}', 'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 10, 'closed_issues': 18, 'state': 'open', 'created_at': '2022-02-11T09:43:27Z', 'updated_at': '2022-02-20T11:37:28Z', 'due_on': '2022-03-05T08:00:00Z', 'closed_at': None}",4,2022-02-18T20:39:05Z,2022-02-20T11:38:04Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
print(pd.__version__)
test_df = pd.DataFrame({
    'Name':['L', 'L', 'L',
                    'M', 'M', 'M', 'M', 'M', 'M'],
    'ID': ['L1', 'L2', 'L3',
              'M1', 'M2', 'M3', 'M4', 'M5', 'M6'],
    'Date': [
        '2005-01-01', '2006-01-01', '2013-01-01', 
        '2005-01-01', '2006-01-01', '2006-01-01', '2017-01-01', '2006-02-01', '2006-03-01'],
    'indicator': [0, 1, 0,
                          0, 1, 0, 0, 1, 0],
    'rolling_sum':[0, 0, 1,
                              0, 0, 0, 0, 1, 2]})
test_df['Date'] = pd.to_datetime(test_df['Date'], errors='coerce')
test_df.groupby('Name').rolling('731D', on='Date')['indicator'].sum().reset_index()
```


### Issue Description

Grouping by a column and then rolling over the grouped dataframe results in `[ValueError: Date must be monotonic]()`. Ultimately, the operation should be able to produce the `rolling_sum` column in the example.

### Expected Behavior

This is not an issue in pandas `1.3.5` but is an issue in `1.4` and higher. I expect this function to create a grouped dataframe and to then perform the rolling summation on the provided column using the date window provided. 

### Installed Versions

<details>


INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.8.12.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.1.0
Version          : Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.4.1
numpy            : 1.22.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 22.0.3
setuptools       : 60.6.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.0.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 6.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None


</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46061/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46061/timeline,,,
25,https://api.github.com/repos/pandas-dev/pandas/issues/46060,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46060/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46060/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46060/events,https://github.com/pandas-dev/pandas/pull/46060,1143640899,PR_kwDOAA0YD84zHXZ6,46060,DOC: Add details to DataFrame.combine_first docstring,"{'login': 'Moisan', 'id': 31669, 'node_id': 'MDQ6VXNlcjMxNjY5', 'avatar_url': 'https://avatars.githubusercontent.com/u/31669?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Moisan', 'html_url': 'https://github.com/Moisan', 'followers_url': 'https://api.github.com/users/Moisan/followers', 'following_url': 'https://api.github.com/users/Moisan/following{/other_user}', 'gists_url': 'https://api.github.com/users/Moisan/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Moisan/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Moisan/subscriptions', 'organizations_url': 'https://api.github.com/users/Moisan/orgs', 'repos_url': 'https://api.github.com/users/Moisan/repos', 'events_url': 'https://api.github.com/users/Moisan/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Moisan/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-02-18T19:29:12Z,2022-02-18T21:24:29Z,,CONTRIBUTOR,,"- [x] closes #41704
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46060/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46060/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46060', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46060', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46060.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46060.patch', 'merged_at': None}"
26,https://api.github.com/repos/pandas-dev/pandas/issues/46059,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46059/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46059/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46059/events,https://github.com/pandas-dev/pandas/pull/46059,1143613367,PR_kwDOAA0YD84zHRI3,46059,CI: Test various Pyarrow version on Linux,"{'login': 'mroeschke', 'id': 10647082, 'node_id': 'MDQ6VXNlcjEwNjQ3MDgy', 'avatar_url': 'https://avatars.githubusercontent.com/u/10647082?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mroeschke', 'html_url': 'https://github.com/mroeschke', 'followers_url': 'https://api.github.com/users/mroeschke/followers', 'following_url': 'https://api.github.com/users/mroeschke/following{/other_user}', 'gists_url': 'https://api.github.com/users/mroeschke/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mroeschke/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mroeschke/subscriptions', 'organizations_url': 'https://api.github.com/users/mroeschke/orgs', 'repos_url': 'https://api.github.com/users/mroeschke/repos', 'events_url': 'https://api.github.com/users/mroeschke/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mroeschke/received_events', 'type': 'User', 'site_admin': False}","[{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3MDYwMA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/CI', 'name': 'CI', 'color': 'a2bca7', 'default': False, 'description': 'Continuous Integration'}, {'id': 3303158446, 'node_id': 'MDU6TGFiZWwzMzAzMTU4NDQ2', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Arrow', 'name': 'Arrow', 'color': 'f9d0c4', 'default': False, 'description': ''}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/94', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/94', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/94/labels', 'id': 7667127, 'node_id': 'MI_kwDOAA0YD84AdP23', 'number': 94, 'title': '1.4.2', 'description': 'on-merge: backport to 1.4.x', 'creator': {'login': 'simonjayhawkins', 'id': 13159005, 'node_id': 'MDQ6VXNlcjEzMTU5MDA1', 'avatar_url': 'https://avatars.githubusercontent.com/u/13159005?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/simonjayhawkins', 'html_url': 'https://github.com/simonjayhawkins', 'followers_url': 'https://api.github.com/users/simonjayhawkins/followers', 'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}', 'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions', 'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs', 'repos_url': 'https://api.github.com/users/simonjayhawkins/repos', 'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}', 'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 10, 'closed_issues': 18, 'state': 'open', 'created_at': '2022-02-11T09:43:27Z', 'updated_at': '2022-02-20T11:37:28Z', 'due_on': '2022-03-05T08:00:00Z', 'closed_at': None}",1,2022-02-18T19:09:47Z,2022-02-21T09:46:52Z,,MEMBER,,"- [x] closes #45705 (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature

As discovered in https://github.com/pandas-dev/pandas/pull/46014, pyarrow v2 seems to cause timeouts in read_csv (mamba resolves to v2 but conda resolves to v6 when pyarrow is unpinned, interestingly) so skipping that version.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46059/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46059/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46059', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46059', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46059.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46059.patch', 'merged_at': None}"
27,https://api.github.com/repos/pandas-dev/pandas/issues/46058,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46058/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46058/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46058/events,https://github.com/pandas-dev/pandas/pull/46058,1143499873,PR_kwDOAA0YD84zG3b6,46058,BUG: Fix aligning a DataFrame with a Series with MultiIndex #46001,"{'login': 'johannes-mueller', 'id': 5902745, 'node_id': 'MDQ6VXNlcjU5MDI3NDU=', 'avatar_url': 'https://avatars.githubusercontent.com/u/5902745?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/johannes-mueller', 'html_url': 'https://github.com/johannes-mueller', 'followers_url': 'https://api.github.com/users/johannes-mueller/followers', 'following_url': 'https://api.github.com/users/johannes-mueller/following{/other_user}', 'gists_url': 'https://api.github.com/users/johannes-mueller/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/johannes-mueller/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/johannes-mueller/subscriptions', 'organizations_url': 'https://api.github.com/users/johannes-mueller/orgs', 'repos_url': 'https://api.github.com/users/johannes-mueller/repos', 'events_url': 'https://api.github.com/users/johannes-mueller/events{/privacy}', 'received_events_url': 'https://api.github.com/users/johannes-mueller/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-02-18T17:56:51Z,2022-02-21T10:24:38Z,,CONTRIBUTOR,,"When aligning a DataFrame to a Series we are using Series.reindex() to
broadcast the Series data to the new index.  That introduces NaNs when the new
index rows are not identical to the existing ones, which is not the case when
we introduce a new MultiIndex level.

In this patch we use the same approach as for aligning a Series to another
Series. That means that we have to replicate a part of Series._reindex_indexer
as DataFrame does not have it.

- [x] closes #46001 (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46058/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46058/timeline,,True,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46058', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46058', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46058.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46058.patch', 'merged_at': None}"
28,https://api.github.com/repos/pandas-dev/pandas/issues/46057,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46057/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46057/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46057/events,https://github.com/pandas-dev/pandas/pull/46057,1143476720,PR_kwDOAA0YD84zGyJw,46057,bug: styler latex longtable column count,"{'login': 'attack68', 'id': 24256554, 'node_id': 'MDQ6VXNlcjI0MjU2NTU0', 'avatar_url': 'https://avatars.githubusercontent.com/u/24256554?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/attack68', 'html_url': 'https://github.com/attack68', 'followers_url': 'https://api.github.com/users/attack68/followers', 'following_url': 'https://api.github.com/users/attack68/following{/other_user}', 'gists_url': 'https://api.github.com/users/attack68/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/attack68/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/attack68/subscriptions', 'organizations_url': 'https://api.github.com/users/attack68/orgs', 'repos_url': 'https://api.github.com/users/attack68/repos', 'events_url': 'https://api.github.com/users/attack68/events{/privacy}', 'received_events_url': 'https://api.github.com/users/attack68/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-02-18T17:43:23Z,2022-02-18T17:48:37Z,,CONTRIBUTOR,,"- [x] closes #46037 
- [x] tests
- [x] whats new
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46057/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46057/timeline,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46057', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46057', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46057.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46057.patch', 'merged_at': None}"
29,https://api.github.com/repos/pandas-dev/pandas/issues/46056,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46056/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46056/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46056/events,https://github.com/pandas-dev/pandas/issues/46056,1143451823,I_kwDOAA0YD85EJ7Cv,46056,BUG: pandas.DataFrame.boxplot layout parameter creates unexpected results,"{'login': 'ryancasburn-KAI', 'id': 63560854, 'node_id': 'MDQ6VXNlcjYzNTYwODU0', 'avatar_url': 'https://avatars.githubusercontent.com/u/63560854?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ryancasburn-KAI', 'html_url': 'https://github.com/ryancasburn-KAI', 'followers_url': 'https://api.github.com/users/ryancasburn-KAI/followers', 'following_url': 'https://api.github.com/users/ryancasburn-KAI/following{/other_user}', 'gists_url': 'https://api.github.com/users/ryancasburn-KAI/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ryancasburn-KAI/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ryancasburn-KAI/subscriptions', 'organizations_url': 'https://api.github.com/users/ryancasburn-KAI/orgs', 'repos_url': 'https://api.github.com/users/ryancasburn-KAI/repos', 'events_url': 'https://api.github.com/users/ryancasburn-KAI/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ryancasburn-KAI/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-02-18T17:26:40Z,2022-02-18T17:28:27Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
# imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# setup df
df1 = pd.DataFrame(np.random.randint(0,100,size=100))
df1[""Name""] = ""df1""

df2 = pd.DataFrame(np.random.randint(0,100,size=100))
df2[""Name""] = ""df2""

df3 = pd.DataFrame(np.random.randint(0,100,size=100))
df3[""Name""] = ""df3""

df4 = pd.DataFrame(np.random.randint(0,100,size=100))
df4[""Name""] = ""df4""

df = pd.concat([df1,df2,df3,df4])

# create boxplot
df.boxplot(0, by=""Name"", layout=(2,2))

plt.show()
```


### Issue Description

The all four boxplots are plotted together in the upper left corner. 
![image](https://user-images.githubusercontent.com/63560854/154732572-09cf5a65-b0a7-4fd8-a3b6-20bb797cadb6.png)


### Expected Behavior

The boxplot documentation describes the layout parameter as ""For example, (3, 5) will display the subplots using 3 columns and 5 rows, starting from the top-left."" 

To me, this indicates that the code above should create four box plots one in each corner. It is unclear what the purpose of this parameter is if all it does is put all the plots in one axes and creates empty axes.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 66e3805b8cabe977f40c05259cc3fcf7ead5687d
python           : 3.7.7.final.0
python-bits      : 32
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.3.5
numpy            : 1.21.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 22.0.3
setuptools       : 40.8.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.5.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46056/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46056/timeline,,,
